### ISSUE TITLE
`quantspec` removed from CRAN

### ISSUE THREAD

**Issue by lbelzile** [tobiaskley/quantspec#2]
Dear author,

Your `quantspec` package has been removed from CRAN on July 1st because the email bounced (there is also an error in a test because of a for zero-length for loop). Do you plan to re-upload the package?

**Comment by tobiaskley** [comment]
Thanks for pointing it out.
I will fix it asap.
Best, Tobias.

Am 2024-07-09 16:31, schrieb Léo Belzile:

**Comment by tobiaskley** [comment]
Back on CRAN since 2024-07-11.
Best, Tobias.
